[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[tool.pylint.format]
max-line-length = 119

[tool.ruff]
line-length = 119
